import { FormData } from '@/types';

export const createInitialFormData = (): FormData => ({
  date: new Date().toISOString().split('T')[0],
  managerName: '',
  shift: 'opening',
  startingTil: '',
  endingTil: '',
  notes: '',
  issues: '',
  openingTasks: {
    brushOutside: false,
    setupCleanTables: false,
    pourHotWaterSoda: false,
    setupSodaMachine: false,
    refillPaperTowels: false,
    setupCondiments: false,
    setupTrashcans: false,
    checkRestrooms: false,
    temperatureACCheck: false,
  },
  closingTasks: {
    shareNumbers: false,
    hotWaterSoda: false,
    removeSoakNozzles: false,
    storeFood: false,
    enoughPrep: false,
    turnOffAC: false,
    allEquipmentOff: false,
    filterFryer: false,
    dumpOilSunday: false,
    lockAllDoors: false,
  },
  prepQuantities: {
    meat: '',
    sauceBatches: '',
    sauceCups: '',
    onions: '',
    tomato: '',
    lettuce: '',
    yellowChiles: '',
    pickles: '',
  },
});
