import { FormData } from '@/types';

export const createInitialFormData = (): FormData => ({
  date: new Date().toISOString().split('T')[0],
  managerName: '',
  shift: 'opening',
  startingTil: 0,
  endingTil: 0,
  notes: '',
  issues: '',
  openingTasks: {
    brushOutside: false,
    setupCleanTables: false,
    pourHotWaterSoda: false,
    setupSodaMachine: false,
    refillPaperTowels: false,
    setupCondiments: false,
    setupTrashcans: false,
    checkRestrooms: false,
    temperatureACCheck: false,
  },
  closingTasks: {
    shareNumbers: false,
    hotWaterSoda: false,
    removeSoakNozzles: false,
    storeFood: false,
    enoughPrep: false,
    turnOffAC: false,
    allEquipmentOff: false,
    filterFryer: false,
    dumpOilSunday: false,
    lockAllDoors: false,
  },
  prepQuantities: {
    meat: 0,
    sauceBatches: 0,
    sauceBottles: 0,
    onions: 0,
    tomato: 0,
    lettuce: 0,
    yellowChiles: 0,
    pickles: 0,
  },
});
